version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKERHUB_USERNAME/devops-fastapi-app:latest .

      - run:
          name: Push Docker Image to DockerHub
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $DOCKERHUB_USERNAME/devops-fastapi-app:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push

