version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install deps
          command: pip install -r src/requirements.txt
      - run:
          name: Run Tests
          command: echo "No tests yet"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
